web/router.ex
defmodule Chat.Router do
  use Chat.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Chat.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Chat do
    pipe_through :browser # Use the default browser stack

    # get "/", TopicController, :index
    # get "/topics/new", TopicController, :new
    # post "/topics", TopicController, :create
    # get "/topics/:id/edit", TopicController, :edit
    # put "/topics/:id", TopicController, :update
    # delete "/topics/:id", TopicController, :delete

    resources "/", TopicController

  end
  scope "/auth", Chat do
    pipe_through :browser
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end


  # Other scopes may use custom stacks.
  # scope "/api", Chat do
  #   pipe_through :api
  # end
end

lib/chat/endpoint.ex
defmodule Chat.Endpoint do
  use Phoenix.Endpoint, otp_app: :chat

  socket "/socket", Chat.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :chat, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_discuss_key",
    signing_salt: "cT+a+2s6"

  plug Chat.Router
end

lib/chat/repo.ex
defmodule Chat.Repo do
  use Ecto.Repo, otp_app: :chat
end

web/models/message.ex
defmodule Chat.Message do
  use Chat.Web, :model

  @derive {Poison.Encoder, only: [:message, :user]}

  schema "messages" do
    field :message, :string
    belongs_to :user, Chat.User
    belongs_to :topic, Chat.Topic

    timestamps()
  end

  def changeset(struct, params) do
    struct
    |> cast(params, [:message])
    |> validate_required([:message])

  end


end

web/models/topic.ex
defmodule Chat.Topic do
  use Chat.Web, :model

  schema "topics" do
    field :title, :string
    belongs_to :user, Chat.User
    has_many :messages, Chat.Message
  end


  def changeset(struct, params \\ %{}) do
    struct
      |> cast(params,[:title])
      |> validate_required([:title])
  end

end

web/models/user.ex
defmodule Chat.User do
  use Chat.Web, :model
  @derive {Poison.Encoder, only: [:email]}
  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string

    has_many :topics, Chat.Topic
    has_many :messages, Chat.Message
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end

end

web/controllers/auth_controller.ex
defmodule Chat.AuthController do
  use Chat.Web, :controller
  plug Ueberauth
  alias Chat.User

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, %{"provider" => provider}) do
    user_changeset = User.changeset(%User{}, %{email: auth.info.email, token: auth.credentials.token, provider: provider})
    signin(conn, user_changeset)
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: topic_path(conn, :index))
  end


  defp signin(conn, user_changeset) do
    case insert(user_changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Signin Successful")
        |> put_session(:user_id, user.id)
        |> redirect(to: topic_path(conn, :index))
      {:error, _user_struct} ->
        conn
        |> put_flash(:error, "Error Signing in the User")
        |> redirect(to: topic_path(conn, :index))

    end
  end

  defp insert(user_changeset) do
    case Repo.get_by(User, email: user_changeset.changes.email) do
      nil -> Repo.insert(user_changeset)
      user -> {:ok, user}
    end
  end

end

web/controllers/topic_controller.ex
defmodule Chat.TopicController do
  use Chat.Web, :controller
  alias Chat.Topic

  plug Chat.Plugs.RequireAuth when action in [:new, :create, :update, :edit, :delete]
  plug :check_topic_owner when action in [:edit, :update, :delete]

  def index(conn, _params ) do
      topics = Repo.all(Topic)
      render conn, "index.html", topics: topics
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    render conn, "show.html", topic: topic
  end

  def new(conn, _params) do
    changeset  = Topic.changeset(%Topic{}, %{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"topic" => topic}) do

    changeset = Topic.changeset(%Topic{},topic)

    changeset = conn.assigns.user
      |> build_assoc(:topics)
      |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, topic} ->
        conn
        |> put_flash(:info, 'Group Created "#{topic.title}" ')
        |> redirect(to: topic_path(conn,:index))
      {:error, changeset} -> render conn, "new.html", changeset: changeset
    end
  end

  def edit(conn, %{"id" => topic_id}) do

    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)

    render conn, "edit.html", changeset: changeset, topic: topic

  end

  def update(conn, %{"id" => topic_id ,"topic" => topic}) do
    changeset = Repo.get(Topic,topic_id) |> Topic.changeset(topic)
      case Repo.update(changeset) do
        {:ok, topic} ->
          conn
          |> put_flash(:info, 'Group Name Updated to "#{topic.title}" ')
          |> redirect(to: topic_path(conn, :index))
        {:error, changeset} -> render conn, "edit.html", changeset: changeset, topic: topic
      end

  end


  def delete(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic,topic_id)
    topic |> Repo.delete!
    conn
    |> put_flash(:info, '"#{topic.title}" Group Deleted')
    |> redirect(to: topic_path(conn, :index))
  end

  def check_topic_owner(%{params: %{"id" => topic_id}} = conn, _params) do
    if Repo.get(Topic, topic_id).user_id == conn.assigns[:user].id do
      conn
    else
      conn
      |> put_flash(:error, "you don't have permission to do that")
      |> redirect(to: topic_path(conn,:index))
      |> halt()
    end

  end

end

web/views/error_view.ex
defmodule Chat.ErrorView do
  use Chat.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Chat.LayoutView do
  use Chat.Web, :view
end

web/views/topic_view.ex
defmodule Chat.TopicView do
   use Chat.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello to IRC!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(Chat.Endpoint,"key",@conn.assigns.user.id) %>"
      <% end %>
    </script>
  </head>

  <body>
    <nav class = "light-blue">
      <div class="nav-wrapper container">
        <a href="/" class = "brand-logo">
          Real-Time Chat Application
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li><%= link "Sign Out", to: auth_path(@conn, :signout) %></li>
          <%else%>
            <li><%= link "Sign In Using Github", to: auth_path(@conn, :request, "github") %></li>
          <%end%>
        </ul>
      </div>

    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </body>
</html>

web/templates/topic/edit.html.eex
<%= form_for @changeset, topic_path(@conn,:update, @topic) ,fn f-> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
  <%= submit "Save Topic Name", class: "btn btn-primary" %>
<% end %>

web/templates/topic/index.html.eex
<h4> Groups </h4>

<ul class="collection">
  <%= for topic <- @topics do%>
    <li class = "collection-item">
      <%= link "#{topic.title}", to: topic_path(@conn, :show, topic) %>
      <div class="right">

        <%=  if (Map.has_key?(@conn.assigns, :user)) and (@conn.assigns.user !== nil) do %>

          <%= if @conn.assigns.user.id == topic.user_id do %>
            <%= link "Edit", to: topic_path(@conn, :edit, topic) %>
            <%= link "Delete", to: topic_path(@conn, :delete, topic), method: :delete %>
          <% end %>
        <% end %>


      </div>
    </li>
  <%end%>
</ul>

<div class="fixed-action-btn">
  <%= link to: topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do%>
  <i class = "material-icons">add</i>
  <%end%>
</div>

web/templates/topic/new.html.eex
<%= form_for @changeset, topic_path(@conn,:create) ,fn f-> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
  <%= submit "Create Topic", class: "btn btn-primary" %>
<% end %>

web/templates/topic/show.html.eex
<h5> <%= @topic.title %> </h5>

<ul id = "message-box" class="collection"></ul>

<div class="input-field">
  <textarea id = "content-area" class="materialize-textarea"></textarea>
  <button id = "send-message-button" class="btn" >Send Message</button>
</div>

<script>
  document.addEventListener("DOMContentLoaded", () => {
      window.createSocketChannel(<%= @topic.id %>);
  });
</script>